apiVersion: v1
kind: Namespace
metadata:
  name: crud-app
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-service
  namespace: crud-app
spec:
  selector:
    app: bitcoin
  type: LoadBalancer
  ports:
    - name: bitcoin
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: bitcoin
  namespace: crud-app
  labels:
    app: bitcoin
spec:
  containers:
    - name: bitcoin
      image: unnamed22090/bitcoin_api
      ports:
        - name: bitcoin
          containerPort: 80
          protocol: TCP
      env:
        - name: TZ
          value: "Asia/Bangkok"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: crud-app
spec:
  selector:
    app: mongo-express
  # type: LoadBalancer
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
      targetPort: 8081
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  namespace: crud-app
  labels:
    app: mongo-express
spec:
  containers:
    - name: mongo-express
      image: mongo-express
      ports:
        - name: mongo-express
          containerPort: 8081
          protocol: TCP
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "root"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "1w2q3e4r5t6y"
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://root:1w2q3e4r5t6y@mongo-service.crud-app.svc.cluster.local:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: crud-app
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: crud-app
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "1w2q3e4r5t6y"
